import { Request, Response, NextFunction } from 'express';
import axios, { AxiosResponse } from 'axios';
import * as types from '../types';
import { db } from '../app'
import * as utils from '../utils'

// Registers a new user in the database and initializes empty profile.
const registerUser = async (req: Request, res: Response, next: NextFunction) => {
    // Parse user registration info
    let regInfo: types.UserRegistrationInfo = req.body;
    let newUser: types.User = {
        email: regInfo.auth.email,
        passHash: utils.hash(regInfo.auth.pass),
        bio: regInfo.bio
    };
    // Add user to database
    let usersRef = db.ref("/users");
    let newUserRef = usersRef.push(newUser);
    // Get unique user ID generated by firebase
    let userID = newUserRef.key;

    // Create empty profile for new user
    let profileRef = db.ref("/profiles");
    profileRef.set({
        [userID]: []
    });

    // Generate new API token
    let token = utils.hash(userID);
    let hashedToken = utils.hash(token);

    // Store hashedToken in database
    let tokensRef = db.ref("/tokens");
    tokensRef.set({
        [hashedToken]: userID
    });

    // Return token to user
    let tokenResponse: types.ClientAuthToken = {
        token: token
    };

    return res.status(201).json(tokenResponse);
};

export default { registerUser };
